// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  angular.module('angular-paylogic-shopping-service', ['ngResource', 'base64']).provider('paylogicShoppingService', function() {
    var options;
    options = {};
    this.configure = (function(_this) {
      return function(opts) {
        angular.extend(options, opts);
      };
    })(this);
    this.$get = (function(_this) {
      return function($http, $base64, Event, Product, Bill, Order) {
        var auth;
        auth = $base64.encode(options.apiKey + ':' + options.apiSecret);
        $http.defaults.headers.common.Authorization = 'Basic ' + auth;
        return {
          events: Event,
          products: Product,
          bill: Bill,
          orders: Order
        };
      };
    })(this);
    return this;
  }).constant('baseUrl', 'https://shopping-service.sandbox.paylogic.com/');

  'use strict';

  angular.module('angular-paylogic-shopping-service').factory('Bill', function($resource, baseUrl) {
    var resourceUrl;
    resourceUrl = baseUrl + 'bill';
    return $resource(resourceUrl, null);
  });

  'use strict';

  angular.module('angular-paylogic-shopping-service').factory('Event', function($resource, baseUrl) {
    var resourceUrl;
    resourceUrl = baseUrl + 'events/:eventUid';
    return $resource(resourceUrl, null, {
      query: {
        method: 'GET'
      }
    });
  });

  'use strict';

  angular.module('angular-paylogic-shopping-service').factory('Order', function($resource, baseUrl) {
    var resourceUrl;
    resourceUrl = baseUrl + 'orders/:orderUid';
    return $resource(resourceUrl, null, {
      create: {
        method: 'POST'
      }
    });
  });

  'use strict';

  angular.module('angular-paylogic-shopping-service').factory('Product', function($resource, baseUrl) {
    var resourceUrl;
    resourceUrl = baseUrl + 'products/:productUid';
    return $resource(resourceUrl, null, {
      query: {
        method: 'GET'
      }
    });
  });

}).call(this);

//# sourceMappingURL=angular.paylogic.shopping.service.js.map
